# Generated by Django 5.0.1 on 2024-02-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalVoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='en', max_length=30),
        ),
    ]
