# Generated by Django 5.0.1 on 2024-02-22 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalVoice', '0002_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_sentence', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalVoice.language')),
            ],
        ),
        migrations.CreateModel(
            name='OutputTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_sentence', models.TextField()),
                ('context', models.CharField(max_length=255)),
                ('dialect', models.CharField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalVoice.language')),
            ],
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
