# Generated by Django 5.0.1 on 2024-03-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalVoice', '0003_inputtranslation_outputtranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
