# Generated by Django 5.0.1 on 2024-03-05 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalVoice', '0004_alter_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtranslation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outputtranslation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_translations', to=settings.AUTH_USER_MODEL),
        ),
    ]
